// flow-typed signature: 2ffe6c98f9a01bfc419510f8a66a77ae
// flow-typed version: <<STUB>>/faunadb_v2.9.3/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'faunadb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'faunadb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'faunadb/dist/faunadb-min' {
  declare module.exports: any;
}

declare module 'faunadb/dist/faunadb' {
  declare module.exports: any;
}

declare module 'faunadb/src/_json' {
  declare module.exports: any;
}

declare module 'faunadb/src/_util' {
  declare module.exports: any;
}

declare module 'faunadb/src/Client' {
  declare module.exports: any;
}

declare module 'faunadb/src/clientLogger' {
  declare module.exports: any;
}

declare module 'faunadb/src/errors' {
  declare module.exports: any;
}

declare module 'faunadb/src/Expr' {
  declare module.exports: any;
}

declare module 'faunadb/src/PageHelper' {
  declare module.exports: any;
}

declare module 'faunadb/src/query' {
  declare module.exports: any;
}

declare module 'faunadb/src/RequestResult' {
  declare module.exports: any;
}

declare module 'faunadb/src/values' {
  declare module.exports: any;
}

// Filename aliases
declare module 'faunadb/dist/faunadb-min.js' {
  declare module.exports: $Exports<'faunadb/dist/faunadb-min'>;
}
declare module 'faunadb/dist/faunadb.js' {
  declare module.exports: $Exports<'faunadb/dist/faunadb'>;
}
declare module 'faunadb/index' {
  declare module.exports: $Exports<'faunadb'>;
}
declare module 'faunadb/index.js' {
  declare module.exports: $Exports<'faunadb'>;
}
declare module 'faunadb/src/_json.js' {
  declare module.exports: $Exports<'faunadb/src/_json'>;
}
declare module 'faunadb/src/_util.js' {
  declare module.exports: $Exports<'faunadb/src/_util'>;
}
declare module 'faunadb/src/Client.js' {
  declare module.exports: $Exports<'faunadb/src/Client'>;
}
declare module 'faunadb/src/clientLogger.js' {
  declare module.exports: $Exports<'faunadb/src/clientLogger'>;
}
declare module 'faunadb/src/errors.js' {
  declare module.exports: $Exports<'faunadb/src/errors'>;
}
declare module 'faunadb/src/Expr.js' {
  declare module.exports: $Exports<'faunadb/src/Expr'>;
}
declare module 'faunadb/src/PageHelper.js' {
  declare module.exports: $Exports<'faunadb/src/PageHelper'>;
}
declare module 'faunadb/src/query.js' {
  declare module.exports: $Exports<'faunadb/src/query'>;
}
declare module 'faunadb/src/RequestResult.js' {
  declare module.exports: $Exports<'faunadb/src/RequestResult'>;
}
declare module 'faunadb/src/values.js' {
  declare module.exports: $Exports<'faunadb/src/values'>;
}
