// flow-typed signature: dc2dbd88bf203c444092c80d065a1883
// flow-typed version: <<STUB>>/@react-pdf/renderer_v1.6.8/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-pdf/renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-pdf/renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-pdf/renderer/dist/react-pdf.browser.cjs' {
  declare module.exports: any;
}

declare module '@react-pdf/renderer/dist/react-pdf.browser.cjs.min' {
  declare module.exports: any;
}

declare module '@react-pdf/renderer/dist/react-pdf.browser.es' {
  declare module.exports: any;
}

declare module '@react-pdf/renderer/dist/react-pdf.browser.es.min' {
  declare module.exports: any;
}

declare module '@react-pdf/renderer/dist/react-pdf.cjs' {
  declare module.exports: any;
}

declare module '@react-pdf/renderer/dist/react-pdf.cjs.min' {
  declare module.exports: any;
}

declare module '@react-pdf/renderer/dist/react-pdf.es' {
  declare module.exports: any;
}

declare module '@react-pdf/renderer/dist/react-pdf.es.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-pdf/renderer/dist/react-pdf.browser.cjs.js' {
  declare module.exports: $Exports<'@react-pdf/renderer/dist/react-pdf.browser.cjs'>;
}
declare module '@react-pdf/renderer/dist/react-pdf.browser.cjs.min.js' {
  declare module.exports: $Exports<'@react-pdf/renderer/dist/react-pdf.browser.cjs.min'>;
}
declare module '@react-pdf/renderer/dist/react-pdf.browser.es.js' {
  declare module.exports: $Exports<'@react-pdf/renderer/dist/react-pdf.browser.es'>;
}
declare module '@react-pdf/renderer/dist/react-pdf.browser.es.min.js' {
  declare module.exports: $Exports<'@react-pdf/renderer/dist/react-pdf.browser.es.min'>;
}
declare module '@react-pdf/renderer/dist/react-pdf.cjs.js' {
  declare module.exports: $Exports<'@react-pdf/renderer/dist/react-pdf.cjs'>;
}
declare module '@react-pdf/renderer/dist/react-pdf.cjs.min.js' {
  declare module.exports: $Exports<'@react-pdf/renderer/dist/react-pdf.cjs.min'>;
}
declare module '@react-pdf/renderer/dist/react-pdf.es.js' {
  declare module.exports: $Exports<'@react-pdf/renderer/dist/react-pdf.es'>;
}
declare module '@react-pdf/renderer/dist/react-pdf.es.min.js' {
  declare module.exports: $Exports<'@react-pdf/renderer/dist/react-pdf.es.min'>;
}
